version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
  mysqldb:
    image: "mysql:8.0"
    command:
      - --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: medispatch
      MYSQL_USER: devv
      MYSQL_PASSWORD: manchester
      MYSQL_ROOT_PASSWORD: manchester
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./logs:/log


